In [91]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.tree import DecisionTreeClassifier

In [92]:
data = {
    '客户':['客户1','客户2','客户3'],
    '年龄':[65,35,24],
    '性别':['0','1','0'],
    '是否点甜品':['0','1','0']
}
df = pd.DataFrame(data)

In [93]:
df

,客户,年龄,性别,是否点甜品
0,客户1,65,0,0
1,客户2,35,1,1
2,客户3,24,0,0


In [94]:
test_data = {
    '客户':['客户4'],
    '年龄':['33'],
    '性别':['0']
}
test_df = pd.DataFrame(test_data)

In [95]:
test_df

,客户,年龄,性别
0,客户4,33,0


In [96]:
model = DecisionTreeClassifier(random_state=0)

In [97]:
model = model.fit(df[['年龄','性别']],df['是否点甜品'])

In [98]:
prediction = model.predict(test_df[['年龄','性别']])

In [99]:
result = '是' if prediction[0]==1 else '否'

In [100]:
print(f'客户4点甜品吗?:{result}')

客户4点甜品吗?:否


In [101]:
data=pd.read_excel('农村居民人均可支配收入来源2016.xlsx')
data

,地区,工资性收入,经营净收入,财产净收入,转移净收入
0,北京,16637.5,2061.9,1350.1,2260.0
1,天津,12048.1,5309.4,893.7,1824.4
2,河北,6263.2,3970.0,257.5,1428.6
3,山西,5204.4,2729.9,149.0,1999.1
4,内蒙古,2448.9,6215.7,452.6,2491.7
5,辽宁,5071.2,5635.5,257.6,1916.4
6,吉林,2363.1,7558.9,231.8,1969.1
7,黑龙江,2430.5,6425.9,572.7,2402.6
8,上海,18947.9,1387.9,859.6,4325.0
9,江苏,8731.7,5283.1,606.0,2984.8


In [102]:
x=data.iloc[:,1:]
x

,工资性收入,经营净收入,财产净收入,转移净收入
0,16637.5,2061.9,1350.1,2260.0
1,12048.1,5309.4,893.7,1824.4
2,6263.2,3970.0,257.5,1428.6
3,5204.4,2729.9,149.0,1999.1
4,2448.9,6215.7,452.6,2491.7
5,5071.2,5635.5,257.6,1916.4
6,2363.1,7558.9,231.8,1969.1
7,2430.5,6425.9,572.7,2402.6
8,18947.9,1387.9,859.6,4325.0
9,8731.7,5283.1,606.0,2984.8


In [103]:
from sklearn.preprocessing import StandardScaler

In [104]:
scaler=StandardScaler()

In [105]:
scalered_data=scaler.fit_transform(x)
scalered_data

array([[ 2.62267702, -1.90653048,  3.65623472, -0.05290328],
       [ 1.52887926,  0.51994204,  2.00731096, -0.75273157],
       [ 0.15015642, -0.48083311, -0.29121072, -1.38861779],
       [-0.10218878, -1.40741312, -0.68320947, -0.47206122],
       [-0.75891073,  1.1971128 ,  0.41366444,  0.31934239],
       [-0.13393451,  0.76359799, -0.29084943, -0.60492578],
       [-0.77935956,  2.20072724, -0.38406204, -0.52025876],
       [-0.76329603,  1.35417039,  0.84757273,  0.1761957 ],
       [ 3.17331769, -2.41013094,  1.88411135,  3.26469409],
       [ 0.73847728,  0.50029116,  0.96788202,  1.1115493 ],
       [ 2.04276925,  0.75343632,  1.16948138,  0.13683437],
       [-0.31978527, -0.01302265, -0.54700345,  0.56755973],
       [ 0.27456537,  0.90257378, -0.29771393, -0.25067385],
       [-0.16170011,  0.05885622, -0.48305527, -0.01048944],
       [-0.01526935,  1.23514435,  0.07441391, -0.8566776 ],
       [-0.33489548,  0.0221696 , -0.61456453,  0.58587479],
       [-0.3837534 ,  0.

In [106]:
from sklearn.decomposition import PCA

In [107]:
pca=PCA(n_components=1)

In [108]:
data=pca.fit_transform(scalered_data)
data

array([[ 4.33588394],
       [ 1.53736203],
       [-0.46694468],
       [-0.10431271],
       [-0.55472192],
       [-0.7860694 ],
       [-1.74256785],
       [-0.43551643],
       [ 5.26192283],
       [ 1.26240024],
       [ 1.66736332],
       [-0.25754205],
       [-0.44568285],
       [-0.39402814],
       [-0.79480747],
       [-0.31006603],
       [-0.37598829],
       [-0.08226864],
       [ 0.97778119],
       [-0.61802252],
       [-1.17447251],
       [ 0.37012714],
       [-0.1364243 ],
       [-0.87126924],
       [-1.62901512],
       [-1.58629868],
       [-0.18741213],
       [-0.78267223],
       [ 0.17356232],
       [-0.53868768],
       [-1.31161213]])

In [109]:
from sklearn.preprocessing import StandardScaler

In [110]:
scaler=StandardScaler()

In [111]:
scalered_data=scaler.fit_transform(x)

In [112]:
scalered_data

array([[ 2.62267702, -1.90653048,  3.65623472, -0.05290328],
       [ 1.52887926,  0.51994204,  2.00731096, -0.75273157],
       [ 0.15015642, -0.48083311, -0.29121072, -1.38861779],
       [-0.10218878, -1.40741312, -0.68320947, -0.47206122],
       [-0.75891073,  1.1971128 ,  0.41366444,  0.31934239],
       [-0.13393451,  0.76359799, -0.29084943, -0.60492578],
       [-0.77935956,  2.20072724, -0.38406204, -0.52025876],
       [-0.76329603,  1.35417039,  0.84757273,  0.1761957 ],
       [ 3.17331769, -2.41013094,  1.88411135,  3.26469409],
       [ 0.73847728,  0.50029116,  0.96788202,  1.1115493 ],
       [ 2.04276925,  0.75343632,  1.16948138,  0.13683437],
       [-0.31978527, -0.01302265, -0.54700345,  0.56755973],
       [ 0.27456537,  0.90257378, -0.29771393, -0.25067385],
       [-0.16170011,  0.05885622, -0.48305527, -0.01048944],
       [-0.01526935,  1.23514435,  0.07441391, -0.8566776 ],
       [-0.33489548,  0.0221696 , -0.61456453,  0.58587479],
       [-0.3837534 ,  0.

In [113]:
from sklearn.cluster import KMeans

In [114]:
kmeans = KMeans (n_clusters=4, random_state=0, max_iter=500)

In [115]:
kmeans.fit(scalered_data)

D:\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


,n_clusters,4
,init,'k-means++'
,n_init,'auto'
,max_iter,500
,tol,0.0001
,verbose,0
,random_state,0
,copy_x,True
,algorithm,'lloyd'


In [116]:
a = kmeans.labels_

In [117]:
a

array([1, 1, 2, 0, 2, 2, 2, 2, 3, 1, 1, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 2, 2, 0, 0, 0, 0, 2], dtype=int32)

In [118]:
b = pd.Series(a, index=data['地区'].values.ravel()) 
b

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices